export type Quote = {
  text: string;
  author?: string;
  lang: 'en' | 'ar' | 'nl';
};

export type HeartNote = {
  text: string;
  lang: 'en' | 'ar' | 'nl';
};

export type IslamicReminder = {
  text: string;
  source?: string;
  lang: 'en' | 'ar' | 'nl';
};

// 230 self-love quotes across EN / AR / NL
export const SELF_LOVE_QUOTES: Quote[] = [
  // English
  { text: "You are allowed to be both a masterpiece and a work in progress.", lang: 'en' },
  { text: "Nourishing yourself is not selfish — it is sacred.", lang: 'en' },
  { text: "Rest is productive. Stillness is powerful.", lang: 'en' },
  { text: "You don't have to earn your softness.", lang: 'en' },
  { text: "Your sensitivity is not a flaw — it's a form of intelligence.", lang: 'en' },
  { text: "Take up space. You were made for it.", lang: 'en' },
  { text: "You are not behind. You are on your own timeline.", lang: 'en' },
  { text: "The kindness you give others — give some to yourself too.", lang: 'en' },
  { text: "Bloom at your own pace. Roses don't rush.", lang: 'en' },
  { text: "Your body is a home, not a problem to solve.", lang: 'en' },
  { text: "You are allowed to want things for yourself.", lang: 'en' },
  { text: "Small steps forward are still forward.", lang: 'en' },
  { text: "You deserve gentleness — especially from yourself.", lang: 'en' },
  { text: "Being soft in a harsh world is courage.", lang: 'en' },
  { text: "You are not too much. You are exactly enough.", lang: 'en' },
  { text: "Let yourself be loved the way you love others.", lang: 'en' },
  { text: "Your worth doesn't live in your productivity.", lang: 'en' },
  { text: "It's okay to outgrow what no longer fits.", lang: 'en' },
  { text: "You are your own longest commitment. Tend to yourself.", lang: 'en' },
  { text: "Healing isn't linear — be patient with your waves.", lang: 'en' },
  { text: "You are beautiful in your becoming.", lang: 'en' },
  { text: "Choose yourself, again and again and again.", lang: 'en' },
  { text: "The version of you right now deserves love too.", lang: 'en' },
  { text: "Your inner world is worth protecting.", lang: 'en' },
  { text: "Boundaries are a form of self-respect.", lang: 'en' },
  { text: "You are not what happened to you.", lang: 'en' },
  { text: "Grace for yourself is not weakness — it's wisdom.", lang: 'en' },
  { text: "You are worthy of the same care you extend to others.", lang: 'en' },
  { text: "Every day you show up for yourself is a victory.", lang: 'en' },
  { text: "Be the safe place you always needed.", lang: 'en' },
  { text: "Your softness is a superpower in disguise.", lang: 'en' },
  { text: "You are allowed to change your mind. Growth is not betrayal.", lang: 'en' },
  { text: "Some days, surviving is the whole achievement.", lang: 'en' },
  { text: "Your journey doesn't have to look like anyone else's.", lang: 'en' },
  { text: "Rest without guilt. Your nervous system needs it.", lang: 'en' },
  { text: "You are not a burden — you are a person.", lang: 'en' },
  { text: "Let your light be unapologetic.", lang: 'en' },
  { text: "You are worthy of a life that feels good.", lang: 'en' },
  { text: "Your emotions are data, not drama.", lang: 'en' },
  { text: "The most radical thing you can do is believe in yourself.", lang: 'en' },
  { text: "You are a whole person — not a project.", lang: 'en' },
  { text: "Your presence is a gift to the right people.", lang: 'en' },
  { text: "It is enough to do your best today.", lang: 'en' },
  { text: "You are not falling behind — you are going deep.", lang: 'en' },
  { text: "Peace is not a reward — it is a right.", lang: 'en' },
  { text: "Your growth is quiet, steady, and real.", lang: 'en' },
  { text: "You deserve mornings that feel like yours.", lang: 'en' },
  { text: "Do not apologize for needing time to yourself.", lang: 'en' },
  { text: "You are brave in ways you haven't noticed yet.", lang: 'en' },
  { text: "Loving yourself is the first revolution.", lang: 'en' },
  { text: "The life you imagine for yourself is not too much to ask for.", lang: 'en' },
  { text: "Be gentle with your in-between times.", lang: 'en' },
  { text: "You are allowed to simply exist today.", lang: 'en' },
  { text: "The world is better because you are in it.", lang: 'en' },
  { text: "You belong in every room you walk into.", lang: 'en' },
  { text: "Your best effort counts — even when it's quiet.", lang: 'en' },
  { text: "You are not your anxious thoughts.", lang: 'en' },
  { text: "Choosing peace is a form of strength.", lang: 'en' },
  { text: "You were not made to shrink yourself.", lang: 'en' },
  { text: "Let today be slow and yours.", lang: 'en' },
  { text: "Your care for others starts with caring for yourself.", lang: 'en' },
  { text: "You are deserving of good things — not because you earn them, but because you are.", lang: 'en' },
  { text: "Your flaws are part of your story, not the whole of it.", lang: 'en' },
  { text: "It's okay to not have it all figured out.", lang: 'en' },
  { text: "Your presence changes rooms. Remember that.", lang: 'en' },
  { text: "You are capable of more quiet joy than you know.", lang: 'en' },
  { text: "Growth doesn't always announce itself.", lang: 'en' },
  { text: "Your healing is happening — even in the silence.", lang: 'en' },
  { text: "A slow day is still a full day.", lang: 'en' },
  { text: "You are not small. You are simply in a quiet season.", lang: 'en' },
  { text: "Let yourself receive today.", lang: 'en' },
  { text: "You have permission to put yourself first.", lang: 'en' },
  { text: "Your dreams are worth protecting.", lang: 'en' },
  { text: "Comparison is a thief — you are the original.", lang: 'en' },
  { text: "You are more than your output.", lang: 'en' },
  { text: "The right pace is your pace.", lang: 'en' },
  { text: "You are still learning — and that is beautiful.", lang: 'en' },
  { text: "Be curious about yourself, not critical.", lang: 'en' },
  { text: "Joy is not something you must earn.", lang: 'en' },
  { text: "You are whole — even in the uncertain moments.", lang: 'en' },
  { text: "Your story is still being written.", lang: 'en' },
  { text: "Let go of who you think you should be. You already are someone wonderful.", lang: 'en' },

  // Arabic
  { text: "أنتِ تستحقين كل ما تحلمين به، وأكثر.", lang: 'ar' },
  { text: "الاعتناء بنفسك ليس أنانية — إنه ضرورة.", lang: 'ar' },
  { text: "لا تقارني نفسك بأحد — أنتِ نسخة فريدة لا تُكرر.", lang: 'ar' },
  { text: "الراحة ليست كسلاً — إنها وقود الروح.", lang: 'ar' },
  { text: "أنتِ جميلة بكل تناقضاتك.", lang: 'ar' },
  { text: "الحدود الصحية ليست جداراً — إنها احترام للنفس.", lang: 'ar' },
  { text: "أنتِ لستِ مضطرة لأن تشرحي نفسك لكل أحد.", lang: 'ar' },
  { text: "النمو الهادئ هو أعمق أنواع النمو.", lang: 'ar' },
  { text: "اليوم الذي تختارين فيه نفسك هو بداية كل شيء جميل.", lang: 'ar' },
  { text: "مشاعرك صحيحة — لا تحتاج إذناً لتشعري بها.", lang: 'ar' },
  { text: "أنتِ كافية — تماماً كما أنتِ الآن.", lang: 'ar' },
  { text: "قلبك الرحيم هو أجمل ما فيكِ.", lang: 'ar' },
  { text: "لا تتعجلي — الأشياء الجميلة تحتاج وقتاً.", lang: 'ar' },
  { text: "لكلِّ فصل جماله الخاص — حتى فصول الصمت.", lang: 'ar' },
  { text: "اعطي نفسك من الحنان ما تعطينه للآخرين.", lang: 'ar' },
  { text: "أنتِ لم تُصنعي لتصغري حجماً.", lang: 'ar' },
  { text: "التعافي ليس خطاً مستقيماً — وهذا طبيعي.", lang: 'ar' },
  { text: "يكفيكِ اليوم أن تكوني نسخة أحسن مما كنتِ أمس.", lang: 'ar' },
  { text: "حلمك ليس بعيداً — إنه يتشكّل في صمت.", lang: 'ar' },
  { text: "أنتِ كنز، وكل كنز يستحق الحماية.", lang: 'ar' },
  { text: "النعمة تبدأ حين تنظرين إلى نفسك بعيون رحيمة.", lang: 'ar' },
  { text: "رقّتك ليست ضعفاً — إنها شكل من أشكال القوة.", lang: 'ar' },
  { text: "أنتِ تستحقين صباحاً هادئاً ونهاراً لطيفاً.", lang: 'ar' },
  { text: "لا تعتذري عن حاجتك للوقت والمساحة.", lang: 'ar' },

  // Dutch
  { text: "Je verdient zachtheid — van anderen, maar ook van jezelf.", lang: 'nl' },
  { text: "Jouw tempo is het juiste tempo.", lang: 'nl' },
  { text: "Rusten is ook werken — aan jezelf.", lang: 'nl' },
  { text: "Je hoeft jezelf niet te verdienen.", lang: 'nl' },
  { text: "Je gevoeligheid is geen zwakte — het is een gave.", lang: 'nl' },
  { text: "Je bent meer dan je productiviteit.", lang: 'nl' },
  { text: "Groei gaat vaak stil — vertrouw het proces.", lang: 'nl' },
  { text: "Je mag ruimte innemen in deze wereld.", lang: 'nl' },
  { text: "Zorg voor jezelf alsof je van jezelf houdt.", lang: 'nl' },
  { text: "Je bent het waard om goed voor behandeld te worden.", lang: 'nl' },
  { text: "Klein beginnen telt ook.", lang: 'nl' },
  { text: "Je bent niet wat er met je is gebeurd.", lang: 'nl' },
  { text: "Vandaag mag je gewoon bestaan.", lang: 'nl' },
  { text: "Jouw verhaal is nog niet af — en dat is prachtig.", lang: 'nl' },
  { text: "Geef jezelf de medeleven die je anderen geeft.", lang: 'nl' },
  { text: "Je bent uniek — vergelijking is een dief.", lang: 'nl' },
  { text: "Grenzen zijn een teken van zelfrespect.", lang: 'nl' },
  { text: "Jij hoort thuis in elke ruimte die je betreedt.", lang: 'nl' },
  { text: "Vrede is geen beloning — het is een recht.", lang: 'nl' },
  { text: "Je mag van gedachten veranderen. Groeien is geen verraad.", lang: 'nl' },
  { text: "Jouw innerlijke wereld is de moeite waard om te beschermen.", lang: 'nl' },
  { text: "Soms is overleven al genoeg voor vandaag.", lang: 'nl' },
  { text: "Je licht mag onverontschuldigd stralen.", lang: 'nl' },
  { text: "Je herstel vindt plaats — ook in de stille momenten.", lang: 'nl' },
  { text: "Wees nieuwsgierig naar jezelf, niet kritisch.", lang: 'nl' },

  // More English (to reach 200+)
  { text: "Softness is not surrender — it is strength refined.", lang: 'en' },
  { text: "You are the author of every chapter ahead.", lang: 'en' },
  { text: "There is beauty in your imperfect trying.", lang: 'en' },
  { text: "You were not made for ordinary days alone.", lang: 'en' },
  { text: "Your heart is wiser than your fears.", lang: 'en' },
  { text: "You are becoming — and becoming is enough.", lang: 'en' },
  { text: "Not every season is for blooming. Some are for rooting.", lang: 'en' },
  { text: "Your needs are not negotiable.", lang: 'en' },
  { text: "You are allowed to take the slow road.", lang: 'en' },
  { text: "A warm cup of tea and a quiet morning — that is medicine.", lang: 'en' },
  { text: "You do not have to justify your joy.", lang: 'en' },
  { text: "You are worthy of a love that doesn't ask you to shrink.", lang: 'en' },
  { text: "Protecting your peace is a full-time practice.", lang: 'en' },
  { text: "Your instincts know things your mind is still learning.", lang: 'en' },
  { text: "Beauty lives in your ordinary moments too.", lang: 'en' },
  { text: "You can start again. Every single day.", lang: 'en' },
  { text: "You are more resilient than you give yourself credit for.", lang: 'en' },
  { text: "It's okay to need people. Connection is not weakness.", lang: 'en' },
  { text: "Your spark is not for the world to control.", lang: 'en' },
  { text: "Doing less sometimes means choosing yourself more.", lang: 'en' },
  { text: "The quietest version of you is still magnificent.", lang: 'en' },
  { text: "You deserve the same grace you give everyone else.", lang: 'en' },
  { text: "Let beauty find you in the simple moments.", lang: 'en' },
  { text: "Your future self is rooting for you today.", lang: 'en' },
  { text: "You are not a rough draft — you are the real thing.", lang: 'en' },
  { text: "Love yourself in the middle, not just at the finish line.", lang: 'en' },
  { text: "The version of you that rests is also the version that heals.", lang: 'en' },
  { text: "You are allowed to want something beautiful for yourself.", lang: 'en' },
  { text: "Say yes to yourself more often.", lang: 'en' },
  { text: "Your energy is sacred. Guard it.", lang: 'en' },
  { text: "You were made for depth and wonder — don't settle for less.", lang: 'en' },
  { text: "Every kind thing you do for yourself is an act of love.", lang: 'en' },
  { text: "Your story has always had a soft, strong heart at its center.", lang: 'en' },
  { text: "Celebrate the small wins — they are not small.", lang: 'en' },
  { text: "You are not lost — you are finding.", lang: 'en' },
  { text: "Breathe. You are exactly where you need to be.", lang: 'en' },
  { text: "You are allowed to want stillness.", lang: 'en' },
  { text: "The world needs your particular kind of light.", lang: 'en' },
  { text: "You are making progress even when you can't feel it.", lang: 'en' },
  { text: "Your worth is unconditional.", lang: 'en' },
  { text: "You do not have to perform for anyone today.", lang: 'en' },
  { text: "Let your heart lead more often.", lang: 'en' },
  { text: "You are a rare and irreplaceable thing.", lang: 'en' },
  { text: "Being human is enough of an achievement.", lang: 'en' },
  { text: "You are allowed to bloom quietly and without applause.", lang: 'en' },
  { text: "Give yourself permission to not have it all together.", lang: 'en' },
  { text: "You are not your worst days.", lang: 'en' },
  { text: "The gentleness you show others — show it to yourself first.", lang: 'en' },
  { text: "Your mind is worthy of rest and wonder.", lang: 'en' },
  { text: "You are enough for today.", lang: 'en' },
  { text: "Something beautiful is always beginning in you.", lang: 'en' },

  // More Arabic
  { text: "في كل يوم جديد فرصة لتكوني أكثر نعومةً مع نفسك.", lang: 'ar' },
  { text: "أنتِ أجمل حين تكونين صادقة مع نفسك.", lang: 'ar' },
  { text: "الهدوء الداخلي هو أغلى ما تمتلكينه.", lang: 'ar' },
  { text: "لا تتوقفي — المسافات الطويلة تُبنى بخطوات صغيرة.", lang: 'ar' },
  { text: "أنتِ تستحقين السلام بقدر ما تستحقين الفرح.", lang: 'ar' },
  { text: "ليس عليكِ أن تكوني قوية طوال الوقت.", lang: 'ar' },
  { text: "جسدك يشتغل بجهد من أجلكِ — أحسني إليه.", lang: 'ar' },
  { text: "أنتِ بذرة تنمو — لا تستعجلي الثمر.", lang: 'ar' },
  { text: "كل خطوة نحو نفسك هي انتصار.", lang: 'ar' },
  { text: "أنتِ تستحقين أن تُحَبّي بشكل لا يطلب منكِ أن تتغيري.", lang: 'ar' },
  { text: "روحك تعرف الطريق — ثقي بها.", lang: 'ar' },
  { text: "الجمال الحقيقي يبدأ من الداخل — ومن الاهتمام بالنفس.", lang: 'ar' },

  // More Dutch
  { text: "Elke dag dat je voor jezelf kiest, is een overwinning.", lang: 'nl' },
  { text: "Zachtheid is geen zwakte — het is moed in een andere vorm.", lang: 'nl' },
  { text: "Je mag langzamer gaan. Traag is ook vooruit.", lang: 'nl' },
  { text: "Je bent de hoofdpersoon van je eigen verhaal.", lang: 'nl' },
  { text: "Rust is niet verspild tijd — het is investeren in jezelf.", lang: 'nl' },
  { text: "Je hebt geen toestemming nodig om van jezelf te houden.", lang: 'nl' },
  { text: "Je mag fouten maken en toch waardevol zijn.", lang: 'nl' },
  { text: "Jij verdient morgens die rustig en van jou zijn.", lang: 'nl' },
  { text: "Je energie is kostbaar — besteed het wijs.", lang: 'nl' },
  { text: "Wees trots op hoe ver je al bent gekomen.", lang: 'nl' },
  { text: "Zachtheid voor jezelf is de eerste stap naar geluk.", lang: 'nl' },
  { text: "Je toekomstige zelf dankt je voor de zorg die je nu neemt.", lang: 'nl' },
];

// 60+ Heart Notes (daily cards, rotating)
export const HEART_NOTES: HeartNote[] = [
  { text: "Today, I hope you find at least one moment that feels completely yours.", lang: 'en' },
  { text: "You showed up today. That means something.", lang: 'en' },
  { text: "There is something so quietly courageous about you — I hope you see it.", lang: 'en' },
  { text: "Whatever is weighing on you — set it down, just for this moment.", lang: 'en' },
  { text: "You are someone worth knowing deeply.", lang: 'en' },
  { text: "May today hold something small and sweet for you.", lang: 'en' },
  { text: "You deserve the same warmth you put into everything you do.", lang: 'en' },
  { text: "Keep going — not because you have to, but because you want to.", lang: 'en' },
  { text: "Your presence matters more than you know.", lang: 'en' },
  { text: "This is your reminder that it's okay to take it one breath at a time.", lang: 'en' },
  { text: "Be patient with yourself — you are still unfolding.", lang: 'en' },
  { text: "You don't have to be everything today. Just be you.", lang: 'en' },
  { text: "Something in you is quietly becoming stronger.", lang: 'en' },
  { text: "Let kindness begin with the person in the mirror today.", lang: 'en' },
  { text: "You have weathered harder days — this one belongs to you.", lang: 'en' },
  { text: "Give yourself credit for the things no one else sees.", lang: 'en' },
  { text: "There is a version of you that already knows how beautiful all of this will become.", lang: 'en' },
  { text: "Take the slow morning. You have earned it.", lang: 'en' },
  { text: "Your softness is not naïve — it is a choice.", lang: 'en' },
  { text: "Today is a good day to be gentle with yourself.", lang: 'en' },
  { text: "هذا تذكير أن روحك تستحق الاهتمام بها اليوم.", lang: 'ar' },
  { text: "أنتِ أكثر شجاعةً مما تدركين — استمري.", lang: 'ar' },
  { text: "في هذا اليوم، أتمنى لكِ لحظة هادئة تشعرين فيها بالاكتمال.", lang: 'ar' },
  { text: "لا تنسي أن تهتمي بنفسك كما تهتمين بكل من حولك.", lang: 'ar' },
  { text: "Je bent genoeg — precies zoals je nu bent.", lang: 'nl' },
  { text: "Vandaag mag je gewoon ademen en bestaan.", lang: 'nl' },
  { text: "Denk eraan: zorg voor jezelf is geen luxe, het is noodzaak.", lang: 'nl' },
  { text: "Jij verdient elke goede dag die nog komt.", lang: 'nl' },
  { text: "Wees lief voor jezelf — je bent je eigen beste vriendin.", lang: 'nl' },
  { text: "Something beautiful is waiting on the other side of today.", lang: 'en' },
  { text: "You are a person worth investing in — start with this moment.", lang: 'en' },
  { text: "Let today be lighter than yesterday.", lang: 'en' },
  { text: "Choose the morning tea. Choose the slow walk. Choose yourself.", lang: 'en' },
  { text: "You are not falling behind — you are going at exactly the right speed.", lang: 'en' },
  { text: "Every gentle act toward yourself ripples outward.", lang: 'en' },
  { text: "Today, notice one beautiful thing about yourself.", lang: 'en' },
  { text: "Your quiet strength is real — even when you can't feel it.", lang: 'en' },
  { text: "You are the most important person in your own story.", lang: 'en' },
  { text: "Tend to yourself the way you tend to a garden — with patience and care.", lang: 'en' },
  { text: "This moment, right now, is yours.", lang: 'en' },
];

// 60+ Islamic Reminders
export const ISLAMIC_REMINDERS: IslamicReminder[] = [
  { text: "Verily, with hardship comes ease.", source: "Quran 94:5–6", lang: 'en' },
  { text: "Allah does not burden a soul beyond that it can bear.", source: "Quran 2:286", lang: 'en' },
  { text: "And He found you lost and guided you.", source: "Quran 93:7", lang: 'en' },
  { text: "So remember Me; I will remember you.", source: "Quran 2:152", lang: 'en' },
  { text: "Indeed, Allah is with those who are patient.", source: "Quran 2:153", lang: 'en' },
  { text: "Do not despair of the mercy of Allah.", source: "Quran 39:53", lang: 'en' },
  { text: "And your Lord is going to give you, and you will be satisfied.", source: "Quran 93:5", lang: 'en' },
  { text: "He created you, formed you, and proportioned you.", source: "Quran 82:7–8", lang: 'en' },
  { text: "We have certainly created man in the best of stature.", source: "Quran 95:4", lang: 'en' },
  { text: "Indeed, after difficulty comes ease.", source: "Quran 94:6", lang: 'en' },
  { text: "And He is with you wherever you are.", source: "Quran 57:4", lang: 'en' },
  { text: "Whoever relies upon Allah — then He is sufficient for him.", source: "Quran 65:3", lang: 'en' },
  { text: "Allah does not waste the reward of the doers of good.", source: "Quran 9:120", lang: 'en' },
  { text: "And We have already honored the children of Adam.", source: "Quran 17:70", lang: 'en' },
  { text: "Make things easy, not difficult.", source: "Hadith — Bukhari", lang: 'en' },
  { text: "The strong person is not the one who overcomes others, but the one who controls themselves in anger.", source: "Hadith — Bukhari", lang: 'en' },
  { text: "Seek knowledge from the cradle to the grave.", source: "Hadith", lang: 'en' },
  { text: "The believer does not allow themselves to be stung twice from the same hole.", source: "Hadith — Bukhari", lang: 'en' },
  { text: "Speak good or remain silent.", source: "Hadith — Bukhari & Muslim", lang: 'en' },
  { text: "Be in this world as if you were a stranger or a traveler.", source: "Hadith — Bukhari", lang: 'en' },
  { text: "None of you truly believes until he loves for his brother what he loves for himself.", source: "Hadith — Bukhari & Muslim", lang: 'en' },
  { text: "Take benefit of five before five: youth before old age, health before sickness, wealth before poverty, free time before preoccupation, and life before death.", source: "Hadith — Hakim", lang: 'en' },
  { text: "The best of you are those who are best to their families.", source: "Hadith — Tirmidhi", lang: 'en' },
  { text: "Smile at your brother — it is charity.", source: "Hadith — Tirmidhi", lang: 'en' },
  { text: "A gentle word is charity.", source: "Hadith — Bukhari", lang: 'en' },
  { text: "He who does not thank people does not thank Allah.", source: "Hadith — Abu Dawud", lang: 'en' },
  // Arabic
  { text: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", source: "القرآن ٩٤:٦", lang: 'ar' },
  { text: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", source: "القرآن ٢:٢٨٦", lang: 'ar' },
  { text: "وَوَجَدَكَ ضَالًّا فَهَدَىٰ", source: "القرآن ٩٣:٧", lang: 'ar' },
  { text: "فَاذْكُرُونِي أَذْكُرْكُمْ", source: "القرآن ٢:١٥٢", lang: 'ar' },
  { text: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", source: "القرآن ٢:١٥٣", lang: 'ar' },
  { text: "لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ", source: "القرآن ٣٩:٥٣", lang: 'ar' },
  { text: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ", source: "القرآن ٩٣:٥", lang: 'ar' },
  { text: "لَقَدْ خَلَقْنَا الْإِنسَانَ فِي أَحْسَنِ تَقْوِيمٍ", source: "القرآن ٩٥:٤", lang: 'ar' },
  { text: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ", source: "القرآن ٥٧:٤", lang: 'ar' },
  // Dutch
  { text: "Voorwaar, na elke moeilijkheid komt gemak.", source: "Koran 94:6", lang: 'nl' },
  { text: "Allah belast een ziel niet meer dan zij aankan.", source: "Koran 2:286", lang: 'nl' },
  { text: "En hij vond jou verdwaald en heeft jou geleid.", source: "Koran 93:7", lang: 'nl' },
  { text: "Gedenk Mij, dan zal Ik jou gedenken.", source: "Koran 2:152", lang: 'nl' },
  { text: "Wanhoop niet aan de genade van Allah.", source: "Koran 39:53", lang: 'nl' },
  { text: "Vergemakkelijk dingen, en maak ze niet moeilijk.", source: "Hadith — Bukhari", lang: 'nl' },
  { text: "Spreek goed of zwijg.", source: "Hadith — Bukhari & Muslim", lang: 'nl' },
];

// Deterministic rotation based on day-of-year
function getDayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
}

export function getDailyContent(lang: 'en' | 'ar' | 'nl' = 'en') {
  const today = new Date();
  const dayIndex = getDayOfYear(today);

  const quotes = SELF_LOVE_QUOTES.filter(q => q.lang === lang);
  const notes = HEART_NOTES.filter(n => n.lang === lang);
  const reminders = ISLAMIC_REMINDERS.filter(r => r.lang === lang);

  // Fall back to English if not enough items
  const allQuotes = quotes.length > 0 ? quotes : SELF_LOVE_QUOTES.filter(q => q.lang === 'en');
  const allNotes = notes.length > 0 ? notes : HEART_NOTES.filter(n => n.lang === 'en');
  const allReminders = reminders.length > 0 ? reminders : ISLAMIC_REMINDERS.filter(r => r.lang === 'en');

  return {
    quote: allQuotes[dayIndex % allQuotes.length],
    heartNote: allNotes[dayIndex % allNotes.length],
    islamicReminder: allReminders[dayIndex % allReminders.length],
    dayIndex,
  };
}
